name: .NET Core Action
on:  push      
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: dotnet Build DxfLib
        run: dotnet build DxfLib/DxfLib.csproj -c Release
      - name: dotnet Build WebAsp
        run: dotnet build WebAsp/WebAsp.csproj -c Release
      - name: dotnet Publish
        run: dotnet publish WebAsp/WebAsp.csproj -c Release --framework netcoreapp3.1 --runtime win-x64
        # make an artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: build
          path: /home/runner/work/DxfTest/DxfTest/WebAsp/bin/Release/netcoreapp3.1/win-x64/publish/
  upload:
    name: FTP Deploy
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: build
          path: build
      - name: FTP Deploy To REG.RU
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
            ftp-server: ${{ secrets.FTP_SERVER }}
            ftp-username: ${{ secrets.FTP_USERNAME }}
            ftp-password: ${{ secrets.FTP_PASSWORD }}
            local-dir: 'build/' # sync only build folder
            git-ftp-args: --all # upload all files